spring:
  application:
    name: ingestion
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/everlake}
    username: ${SPRING_DATASOURCE_USERNAME:everlake}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

logging.level.org.springframework.batch: INFO


#insee:
#  token-url: https://api.insee.fr/token
#  base-url: https://api.insee.fr/entreprises/sirene/V3
#  client-id: ${INSEE_CLIENT_ID:}
#  client-secret: ${INSEE_CLIENT_SECRET:}

insee:
  base-url: https://api.insee.fr/api-sirene/3.11
  api-key: ${INSEE_API_KEY:}
