spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/everlake
    username: everlake
    password: secret
  batch.jdbc.initialize-schema: always
